[Design] 메인화면 광고/이벤트 컴포넌트 구현 (메인화면 뷰)
SOPT-all/35-COLLABORATION-WEB-LOTTE_CINEMA pull request #53
Opened 2024-11-23 16:18 UTC by look-back-luca

## 🔥 Related Issues

- close #29 

## 💙 작업 내용

- [x] 이벤트 영역 위에 광고 두 편 영역 UI 구현
- [x] 이벤트 영역 UI 구현 / 스크롤 가능 

## ✅ PR Point

Q. 확장성을 고려해서 이벤트 영역에 광고 8개를 배열로 구현하였는데 이 부분이 하나의 파일에 다 같이 있으면 코드가 너무 길어져서 따로 파일을 만들어서 옮겨야 하는지 -> 그러면 constant 상수 파일로 옮겨야 하나요? 

(심화 / 나중에 해야 할 것)
1. 캐러셀 라이브러리 적용하기 
2. 전체보기 눌렀을 때 새로고침 / 버튼 눌렀을 때 새로고침 

Q. 스크롤 끝까지 하면 왼쪽 영역이 보이는데 2열 크기를 더 키워서 1열이 안 보이게 해야 하는가?
<img width="418" alt="스크린샷 2024-11-24 오전 1 11 12" src="https://github.com/user-attachments/assets/b860ac1c-542a-4d25-a5a1-b59b637ce097">

## 😡 Trouble Shooting

<item.image width="100%" style={{ borderRadius: '4px' }} />
이렇게 svg 파일을 직접 사용할 때는 width / height는 가능한데, 
다른 style 속성을 주는 것이 안되어서 계속 이런저런 삽집을 하다가 결국에는 그냥 
태그 안에다가 style={{속성: 속성값}} 이런 식으로 주는게 제일 편리한 것 같다. 
더 좋은 방법이 있으면 추천 쿠다사이 ... 🤩
* 속성은 카멜케이스로 작성해주기 !! 

깃 허브에서 이 오류가 떠요 ... ㅠㅠ 
Synchronize to forked repo / Build project on pull_request (pull_request) Failing after 22s 

## 👀 스크린샷 / GIF / 링크
<img width="435" alt="스크린샷 2024-11-24 오전 1 12 24" src="https://github.com/user-attachments/assets/741d62e0-1d21-4135-aeb4-6d008d947fb0">

2024-11-24 13:31 UTC, seueooo requested changes
<img width="414" alt="스크린샷 2024-11-24 오후 9 42 11" src="https://github.com/user-attachments/assets/3a356714-da2c-4506-842f-113c21a2e950">

광고 멘트에 폰트 스타일링이 누락된 것 같습니다! 첨부한 피그마 사진 참고해주세용
이해가 어려운 부분이 있으면 언제든 카톡주세요!

2024-11-24 13:31 UTC, seueooo commented on Lotte-Cinema/src/components/mainPage/EventAdvertising.tsx
> +              <item.image width="100%" style={{ borderRadius: '4px' }} />
p1)
<img width="670" alt="스크린샷 2024-11-24 오후 10 11 48" src="https://github.com/user-attachments/assets/e0bee85c-f849-46d9-a543-8d824e72213f">

요기 피그마를 잘 보면, 사진이 아니라 사진을 포함한 리스트에 border-radius가 들어간 걸 볼 수 있어요!
이미지가 아니라 svg 컴포넌트 형식이라 리스트 전체에 radius를 줘도 안먹는 것 같은데, 확인해보니까 이미지와 정보를 감싸는 리스트 스타일에 overflow: hidden;을 주면 해결되네요!

2024-11-24 13:31 UTC, seueooo commented on Lotte-Cinema/src/components/mainPage/SideAdvertisement.tsx
> +    </S.AdsContainer>
p3) 여기도,,, 넓이를 전체 레이아웃의 90%으로 맞추면 얼추 피그마랑 비슷하게 보이지만, 정확한 구현을 위해 width는 100%로 주고 컨테이너의 패딩값으로 피그마에 나와있는 간격을 설정해주면 좋을 것 같아요!

2024-11-25 02:54 UTC, look-back-luca commented on Lotte-Cinema/src/components/mainPage/EventAdvertising.tsx
> +              <item.image width="100%" style={{ borderRadius: '4px' }} />
천재다

2024-11-25 04:30 UTC, gonn-i approved these changes
굿! 한서 언니 코리 내용과 거의 같아서 간략하게 적었어요! 
이제 프레임은 뚝딱 만드는군여 아주 굿굿 🏃🏻‍♂️🏃🏻

2024-11-25 04:30 UTC, gonn-i commented on Lotte-Cinema/src/assets/svg/IcArrowRightGray0910.tsx
> +import * as React from "react";
p1: 아마 코드 vs code 들어가서 보면 여기가 흐릿할텐데요 이게 임포트한 내용을 실질적으로 사용하지 않아서 never used 경고로 인해, build 시 오류가 발생하고 자동 배포가 되지 않아서! pr에서 질문 남긴 상황이 나옵니다!! 
그래서 앞으로는 요기 1번줄 지워주시면 됩니당 !!

2024-11-25 04:30 UTC, gonn-i commented on Lotte-Cinema/src/assets/svg/ImgThumbnailSmallKoreasalefesta.tsx
> +import * as React from "react";
p1: 얘도!!! 삭제 마찬가지로 svg 안에 다 삭제 해줘용!!

2024-11-25 04:30 UTC, gonn-i commented on Lotte-Cinema/src/components/mainPage/EventAdvertising.tsx
> +    display: flex;
p5: 시멘틱 태그 적재적소에 쓴거 너무 좋아요!! 굿굿 👍

2024-11-27 07:46 UTC, look-back-luca commented
> 광고 멘트에 폰트 스타일링이 누락된 것 같습니다! 첨부한 피그마 사진 참고해주세용 이해가 어려운 부분이 있으면 언제든 카톡주세요!
헐 바로 수정해서 반영했습니다

2024-11-27 07:46 UTC, look-back-luca commented on Lotte-Cinema/src/assets/svg/IcArrowRightGray0910.tsx
> +import * as React from "react";
헐 당장 전부 삭제하겠습니다

2024-11-27 07:48 UTC, look-back-luca commented on Lotte-Cinema/src/components/mainPage/EventAdvertising.tsx
> +              <item.image width="100%" style={{ borderRadius: '4px' }} />
수정해서 반영했습니다 !!!!

2024-11-27 07:48 UTC, look-back-luca commented on Lotte-Cinema/src/components/mainPage/EventAdvertising.tsx
> +      image: ImgThumbnailSmallPolarbear,
반영했습니다!!!!

2024-11-27 08:38 UTC, look-back-luca commented on Lotte-Cinema/src/components/mainPage/EventAdvertising.tsx
> +    grid-template-columns: repeat(2, 83.89%);
반영했습니다 !!

2024-11-27 08:40 UTC, seueooo approved these changes
굿굿 완전 씨박 정완

2024-11-27 08:49 UTC, look-back-luca commented on Lotte-Cinema/src/components/mainPage/SideAdvertisement.tsx
> +    </S.AdsContainer>
수정했습니다 !!

2024-11-27 08:50 UTC, merged